### ISSUE TITLE
**Add Relationship type support to console**

### ISSUE THREAD

**Issue by jbcraine** [mucsci-students/2020fa-420-GreenStringBean#44]
- [x] Include type (-c/-a/-r/-i) in command
- [x] If no type given, display error message

Size Estimate: 1
Primary: Emily
Secondary: Jeremy
Time taken: 5 minutes

**Comment by mruchalski280** [comment]
Console still uses old relationship type (c/a/g/i), needs to be updated to types used by backend (a/c/g/r)
